name: Backmerge from qa
on:
  push:
    branches:
      - qa
jobs:
  merge-main-back-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Set Git config
        run: |
          git config --local user.email "github@wednesday.is"
          git config --local user.name "Github Actions"
      - name: Merge qa back to dev
        run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff qa -m "Auto-merge qa back to dev"
          git push
