name: PRs to master
on: 
  push:
    branches: 
      - qa
jobs:
  merge-master-back-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "github@wednesday.is"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff qa -m "Auto-merge master back to dev"
          git push